# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oathqquser',
            name='user',
        ),
        migrations.DeleteModel(
            name='OAthQQUser',
        ),
    ]
